# Generated by Django 4.1.5 on 2023-01-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('description', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('added_date', models.DateTimeField()),
                ('added_by', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Categories',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Dealercust',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('name', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Name', max_length=255, null=True)),
                ('email', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Email', max_length=255, null=True)),
                ('contact', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Contact', max_length=255, null=True)),
                ('address', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('added_date', models.DateTimeField()),
                ('added_by', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
            ],
            options={
                'db_table': 'DealerCust',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Product', max_length=255, null=True)),
                ('category', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Category', max_length=255, null=True)),
                ('description', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Description', max_length=255, null=True)),
                ('rate', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Rate', max_length=255, null=True)),
                ('selling_price', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Selling_price', max_length=255, null=True)),
                ('quantity', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Quantity', max_length=255, null=True)),
                ('added_date', models.DateTimeField(blank=True, db_column='Added_date', null=True)),
                ('added_by', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Added_by', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Products',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TransactionDetails',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('product_name', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('rate', models.IntegerField(blank=True, null=True)),
                ('qty', models.IntegerField(blank=True, db_column='Qty', null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('dea_cust_name', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('added_date', models.DateTimeField()),
                ('added_by', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('invoice_id', models.IntegerField(blank=True, db_column='Invoice_id', null=True)),
                ('profit', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Profit', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Transaction Details',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('dea_cust_name', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('grandtotal', models.IntegerField(blank=True, db_column='grandTotal', null=True)),
                ('transaction_date', models.DateTimeField()),
                ('discount', models.IntegerField(blank=True, null=True)),
                ('added_by', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('paid_amount', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Paid_amount', max_length=255, null=True)),
                ('return_amount', models.IntegerField(blank=True, db_column='Return_amount', null=True)),
                ('total_profit', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Total_Profit', max_length=255, null=True)),
                ('paid', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Paid', max_length=255, null=True)),
                ('taken', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Taken', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Transactions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TransactionTracker',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('transaction_id', models.IntegerField(blank=True, db_column='Transaction_id', null=True)),
                ('paid_amount', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Paid_amount', max_length=255, null=True)),
                ('added_date', models.DateTimeField(db_column='Added_date')),
                ('updated_by', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Updated_by', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Transaction Tracker',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('user', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='User', max_length=255, null=True)),
                ('contact', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Contact', max_length=255, null=True)),
                ('gender', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Gender', max_length=255, null=True)),
                ('added_by', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Added_by', max_length=255, null=True)),
                ('type', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Type', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Users',
                'managed': True,
            },
        ),
    ]
